# Generated by Django 4.2.3 on 2025-08-07 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Protein",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("name", models.TextField(null=True)),
                ("moa", models.TextField(null=True)),
                ("evidence", models.TextField(null=True)),
                ("moa_category", models.TextField(null=True)),
                ("defence_subtype", models.TextField(null=True)),
                ("sequence", models.TextField(null=True)),
                ("doi", models.TextField(null=True)),
                ("multicomponent", models.TextField(null=True)),
                ("pdb", models.TextField(null=True)),
                ("pdb_filename", models.TextField(null=True)),
                ("pdb_blob", models.BinaryField(null=True)),
                ("structure_type", models.TextField(null=True)),
                ("existing_pfams", models.TextField(null=True)),
                ("euk_virus_homologs_filename", models.TextField(null=True)),
                ("euk_virus_homologs_blob", models.BinaryField(null=True)),
                ("protein_source_name", models.TextField(null=True)),
                ("protein_source_link", models.TextField(null=True)),
                ("pred_secondary_structure_file", models.TextField(null=True)),
                ("pred_secondary_structure_blob", models.BinaryField(null=True)),
            ],
            options={
                "db_table": "protein",
            },
        ),
        migrations.CreateModel(
            name="ProteinPfams",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("pfam_name", models.TextField()),
                ("pfam_accession", models.TextField()),
                ("pfam_length", models.IntegerField()),
                ("e_value", models.FloatField()),
                ("hmm_from", models.IntegerField()),
                ("hmm_to", models.IntegerField()),
                ("ali_from", models.IntegerField()),
                ("ali_to", models.IntegerField()),
                ("env_from", models.IntegerField()),
                ("env_to", models.IntegerField()),
                (
                    "protein",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="explorer.protein",
                    ),
                ),
            ],
            options={
                "db_table": "protein_pfams",
            },
        ),
        migrations.CreateModel(
            name="ProteinDefences",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("defence_name", models.TextField(null=True)),
                ("defence_link", models.TextField(null=True)),
                (
                    "protein",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="explorer.protein",
                    ),
                ),
            ],
            options={
                "db_table": "protein_defence",
            },
        ),
    ]
